version: '3.8'
services:
  nifi:
    image: apache/nifi:1.24.0
    ports:
      - "8443:8443"
      - "8080:8080"
      - "8081:8081"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - nifi_flowfile_repo:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repo:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repo:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/templates:/opt/nifi/nifi-current/conf/templates:ro
    command: >
      bash -c "
        /opt/nifi/scripts/start.sh &
        sleep 120   # dale 2m para que arranque por completo
        wait
      "

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123456789
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/init:/etc/grafana/init
    depends_on:
      - influxdb
    command: >
      bash -c "
        /etc/grafana/init/wait-for-influx.sh &&
        /run.sh
      "

  data-generator:
    build: ./python
    depends_on:
      - nifi
    command: >
      bash -c "
        echo 'Waiting for NiFi on port 8081…' &&
        until nc -z nifi 8081; do
          echo 'port 8081 not ready yet'
          sleep 2
        done &&
        echo 'NiFi ready, starting generator' &&
        python data_generator.py
      "
    restart: unless-stopped

volumes:
  nifi_flowfile_repo:
  nifi_content_repo:
  nifi_provenance_repo:
  influxdb_data:
  grafana_data:
