apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: c8a9bdda-28d1-48f4-a13c-a9fc93371866
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: metrics
      httpMode: POST
    secureJsonData:
      token: mytoken123456789
